<%@ Page Title="" Language="C#" MasterPageFile="~/AdminManage/Admin.master" AutoEventWireup="true" CodeFile="AddCarousel.aspx.cs" Inherits="AdminManage_AddCarousel" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div style="max-width: 600px; margin: 0 auto;">
    <div style="text-align: center; margin-bottom: 20px;">
        <h1>Add Carousel</h1>
    </div>

    <!-- Form Section -->
    <div style="background-color: #f9f9f9; padding: 20px; border-radius: 5px; margin-bottom: 20px;">
        <div style="margin-bottom: 10px;">
            <label for="FileUpload1">Upload Photo:</label>
            <asp:FileUpload ID="FileUpload1" runat="server" onchange="previewPhoto(event)" />
        </div>
        <img src="#" alt="Preview" id="imagepreview" style="display: none; max-width: 200px; margin-top: 10px;" />
        <div style="margin-top: 20px;">
            <asp:Button ID="btnsave" runat="server" Text="SAVE" OnClick="btnsave_Click" CssClass="btn btn-primary" />
            <asp:Button ID="btnReset" runat="server" Text="RESET" OnClick="btnReset_Click" CssClass="btn btn-secondary" />
        </div>
    </div>



    <!-- GridView Section -->   
    <div style="overflow-y: auto; background-color: #f9f9f9; padding: 20px; border-radius: 5px;">
        <div class="grid">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GridView1_RowDeleting1" OnRowEditing="GridView1_RowEditing" OnRowCancelingEdit="GridView1_RowCancelingEdit1" OnRowUpdating="GridView1_RowUpdating" DataKeyNames="ID">
                <Columns>
                    <asp:TemplateField HeaderText="ID">
                        <ItemTemplate>   
                            <asp:Label ID="Label4" runat="server" Text='<%# Eval("ID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Image">      
                        <ItemTemplate>
<asp:Image ID="imgDisplay" runat="server" ImageUrl='<%# ResolveUrl(string.Format("~/AdminManage/images1/{0}", Eval("Image"))) %>' Width="80px" Height="80px" />
                        </ItemTemplate>     
                        <EditItemTemplate>
                            <asp:FileUpload ID="FileUpload1" runat="server" />   
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
        </div>
    </div>
</div>

<script>
    function previewPhoto(event) {
        var input = event.target;
        var preview = document.getElementById('imagepreview');

        var reader = new FileReader();
        reader.onload = function () {
            preview.src = reader.result;
            preview.style.display = 'block';
        }
        reader.readAsDataURL(input.files[0]);
    }
</script>
</asp:Content>



